/**
 * LOCATIONS CONFIGURATION
 * Add, edit, or remove entries to configure locations displayed on the map.
 *
 * Required fields:
 *   - name: Location name
 *   - description: Brief description
 *   - image: Image URL (must be accessible)
 *   - url: External link (opens in new tab)
 *   - lat: Latitude
 *   - lng: Longitude
 */

window.LOCATIONS = [
  {
    name: 'Banco Alimentar Contra a Fome',
    description: 'Organização humanitária que luta contra a fome através da recolha, distribuição e gestão de alimentos a pessoas e famílias em situação de carência em Portugal.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Banco_Alimentar_Contra_a_Fome.jpg/320px-Banco_Alimentar_Contra_a_Fome.jpg',
    url: 'https://www.bancoalimentar.pt',
    lat: 38.7223,
    lng: -9.1393,
  },
  {
    name: 'Cruz Vermelha Portuguesa - Porto',
    description: 'Instituição de utilidade pública dedicada a trabalhos de carácter humanitário, assistência social e cooperação ao desenvolvimento, com presença em toda a região Norte.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://www.cruzvermelha.pt',
    lat: 41.1579,
    lng: -8.6291,
  },
  {
    name: 'Fundação Calouste Gulbenkian',
    description: 'Fundação privada de utilidade pública que promove atividades em arte, caridade e ciência. Com delegação em Lisboa, desenvolve projetos sociais e culturais em toda Portugal.',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Calouste_Gulbenkian_Foundation_logo.svg/320px-Calouste_Gulbenkian_Foundation_logo.svg.png',
    url: 'https://gulbenkian.pt',
    lat: 38.7669,
    lng: -9.1955,
  },
  {
    name: 'Associação Portuguesa de Beneficência - Covilhã',
    description: 'Organização local dedicada ao bem-estar comunitário.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.2833,
    lng: -7.4833,
  },
  {
    name: 'Centro Social Comunitário - Braga',
    description: 'Centro de atividades sociais e culturais.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 41.5505,
    lng: -8.4289,
  },
  {
    name: 'Fundação de Solidariedade - Guarda',
    description: 'Fundação dedicada a projetos de solidariedade social.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.5369,
    lng: -7.2693,
  },
  {
    name: 'Cáritas Diocesana - Covilhã',
    description: 'Organização católica de caridade e ação social.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.3000,
    lng: -7.5000,
  },
  {
    name: 'AAFL - Aveiro',
    description: 'Associação de assistência familiar e laboral.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.6368,
    lng: -8.6418,
  },
  {
    name: 'Voluntários Contra Pobreza - Castelo Branco',
    description: 'Movimento de voluntários contra a pobreza.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.2831,
    lng: -7.4960,
  },
  {
    name: 'Associação de Ajuda Mútua - Leiria',
    description: 'Associação local de ajuda e apoio comunitário.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 39.7436,
    lng: -8.8069,
  },
  {
    name: 'Rede Solidária - Santarém',
    description: 'Rede de solidariedade e bem-estar social.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 39.2368,
    lng: -8.7265,
  },
  {
    name: 'Centro de Inclusão Social - Évora',
    description: 'Centro dedicado à inclusão e integração social.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 38.6644,
    lng: -8.0047,
  },
  {
    name: 'Projeto de Acolhimento - Beja',
    description: 'Projeto de acolhimento e apoio a pessoas vulneráveis.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 38.0161,
    lng: -7.8627,
  },
  {
    name: 'Instituto de Desenvolvimento Social - Faro',
    description: 'Instituto dedicado ao desenvolvimento social regional.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 37.0141,
    lng: -7.9386,
  },
  {
    name: 'Cooperativa de Solidariedade - Setúbal',
    description: 'Cooperativa de trabalho e solidariedade.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 38.5245,
    lng: -8.8872,
  },
  {
    name: 'Associação Vicentina - Viseu',
    description: 'Associação de caridade e ação social vicentina.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.6615,
    lng: -7.3064,
  },
  {
    name: 'Centro Comunitário da Beira Interior - Guarda',
    description: 'Centro comunitário regional.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.5400,
    lng: -7.2600,
  },
  {
    name: 'Fundação para Crianças - Maia',
    description: 'Fundação dedicada ao apoio a crianças e jovens.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 41.2297,
    lng: -8.6232,
  },
  {
    name: 'Centro de Reabilitação Social - Vila Nova de Gaia',
    description: 'Centro de reabilitação e inserção social.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 41.1075,
    lng: -8.6409,
  },
  {
    name: 'Projeto Esperança - Guarda',
    description: 'Projeto social de esperança e renovação.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.5300,
    lng: -7.2800,
  },
  {
    name: 'Associação de Mulheres Trabalhadoras - Covilhã',
    description: 'Associação dedicada aos direitos das mulheres.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.2750,
    lng: -7.5100,
  },
  {
    name: 'Centro de Acolhimento Noturno - Leiria',
    description: 'Centro de acolhimento para pessoas sem abrigo.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 39.7500,
    lng: -8.8100,
  },
  {
    name: 'Programa de Inclusão Digital - Aveiro',
    description: 'Programa de inclusão digital e acesso à tecnologia.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.6400,
    lng: -8.6400,
  },
  {
    name: 'Lar de Idosos Bem-Viver - Covilhã',
    description: 'Lar de acolhimento e cuidados para idosos.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.2900,
    lng: -7.4900,
  },
  {
    name: 'Centro de Dia - Viseu',
    description: 'Centro de dia com atividades e cuidados.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.6600,
    lng: -7.3100,
  },
  {
    name: 'Projeto de Emprego para Jovens - Braga',
    description: 'Programa de capacitação e emprego para jovens.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 41.5500,
    lng: -8.4300,
  },
  {
    name: 'Centro de Saúde Comunitária - Castelo Branco',
    description: 'Centro de saúde e bem-estar comunitário.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 40.2850,
    lng: -7.4950,
  },
  {
    name: 'Associação de Educação Popular - Évora',
    description: 'Associação dedicada à educação e formação popular.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 38.6650,
    lng: -8.0050,
  },
  {
    name: 'Programa de Mediação Familiar - Faro',
    description: 'Programa de mediação e resolução de conflitos familiares.',
    image: 'https://logodix.com/logo/50634.png',
    url: 'https://example.com',
    lat: 37.0150,
    lng: -7.9400,
  },
];

